### ISSUE TITLE
Dune 2.0 / OCaml 4.12 compatible release

### ISSUE THREAD

**Issue by kit-ty-kate** [mirage/irmin-watcher#28]
The latest stable release of `irmin-watcher` isn't compatible with dune 2.0, this in turns makes it incompatible with OCaml 4.12 due to the requirements of `lwt` in that version of the compiler.

The current state of master compiles fine with OCaml 4.12, **no change needed**.
Could there be a release soonish?

**Comment by samoht** [comment]
Unfortunately it is not clear that the current master **works** fine on macOS as the CI is completely broken. Will have a look later this week but last time I looked into it it was a bit of a nightmare.

**Comment by avsm** [comment]
Closed by https://github.com/ocaml/opam-repository/pull/18631
